improve explanation in setup script and show current hostname

diff --git a/core/setup b/core/setup
--- a/core/setup
+++ b/core/setup
@@ -4,6 +4,49 @@ set -e
 
 source "$HOME/okaeri/config/boot"
 
+echo
+echo
+echo "Oakeri - Setup"
+echo "=============="
+echo
+echo "You are about to setup okaeri core tools on your system. You will be asked to enter your "
+echo "password multiple times."
+echo
+echo "The setup process will stop \`packagekit\`. Once setup is complete you should reboot for all"
+echo "the changes to take effect and to restart \`packagekit\`."
+echo
+echo "Your current machine name is: $OKAERI_HOSTNAME"
+echo
+echo
+
+read -p "Do you want to continue? (y/n) " answer
+
+case "$answer" in
+	[Yy]* )
+		echo
+		echo "Continuing..."
+		echo
+		;;
+	[Nn]* )
+		echo
+		echo "Exiting..."
+		echo
+		exit 1
+		;;
+	* )
+		echo
+		echo "Invalid input. Please enter y or n."
+		echo
+		exit 1
+		;;
+esac
+
+echo
+echo
+echo "Oakeri - Stopping packagekit"
+echo "============================"
+echo
+
 service packagekit stop || true
 sudo service packagekit stop || true
 
@@ -33,8 +76,6 @@ echo
 echo
 echo "Oakeri - Setup complete"
 echo "======================="
-echo
-echo "The setup process has stopped packagekit for updates."
 echo
 echo "Restart your machine to complete the setup."
 echo
